### ISSUE TITLE
Not working with Redmine 2.6.0

### ISSUE THREAD

**Issue by piotrsmykaj** [giddie/redmine_default_assign#17]
Installed correctly:

```
$ rake redmine:plugins NAME=redmine_default_assign RAILS_ENV=production
- Migrating redmine_default_assign (Default Assign plugin)...
==  AddDefaultAssigneeToProject: migrating ====================================
-- add_column(:projects, :default_assignee_id, :integer)
   -> 0.3452s
==  AddDefaultAssigneeToProject: migrated (0.3454s) ===========================
```

and restarted Redmine. Plugin configuration appeares, no errors before and after installation but after assigning default user to project or in global plugin settings, I have empty Assignee field when creating new issue.

**Comment by giddie** [comment]
At what point is there no assignee? It is expected behaviour that when filling in the form to create the issue, there is no assignee at that point. When you submit the form, if no assignee was specified in the form, at that point it defaults to the desired assignee. After the issue is created, you should see the default assignee on the issue.

Also, check the plugin configuration and read the text there to see if you want to change that behaviour.

**Comment by piotrsmykaj** [comment]
I tested it now with "Set assignee interactively" and its what I suspected. I haven't seen this option before. Thanks and sorry for oversight.
