### ISSUE TITLE
Cannot default assign to groups  

### ISSUE THREAD

**Issue by GessDraeger** [giddie/redmine_default_assign#36]
I cannot select groups for default assignment in project setting, even when I go to the database and add the id of the group manually, this has no effect. Single user assignment is working properly.

But when I create a new issue I can select the group as asignee.

Can you please help me.
Redmine: 3.3.1
Pluginversion: 0.60

Thank you in advance

**Comment by giddie** [comment]
I've had a play around to see if I can reproduce this problem. I found that in order for the group to appear in the list I had to:

1. Add the group to the project with a role.
2. Reload the project settings form (in order to recalculate the options for the dropdown).

After that, the group was available in the default assignment project setting.

**Comment by GessDraeger** [comment]
Thank you for checking my problem.

The thing is that I additionally use the easyredmine plugin (www.easyredmine.com).
I think the plugins doesn't work properly together.

It's a pity that I cannot select usergroups because your plugin is very impressive and works perfect for single user assignment 👍

**Comment by giddie** [comment]
Could you describe the exact steps you're going through? The groups are added to the project with a role, and you've got group assignment enabled in the main Redmine settings?

**Comment by GessDraeger** [comment]
Yes, I've already done the described steps.
Here are the project-user: 
![grafik](https://cloud.githubusercontent.com/assets/26893803/24790843/2cfda054-1b78-11e7-9f60-5e6ab0a9c2de.png)

and here are the list of possible assignees:
![grafik](https://cloud.githubusercontent.com/assets/26893803/24790929/802ed4d2-1b78-11e7-98c0-a019c86781c1.png)

The group will be considered, because the group-user can be selected as single user.
Do you have any idea how I can solve this?

**Comment by giddie** [comment]
And you've checking that in the Project settings, in the Issue Tracking tab, the "Allow issue assignment to groups" option is checked? Are you able to assign to a group manually when creating an issue?

**Comment by GessDraeger** [comment]
Yes, when I create a new issue, the group can be selected:
![grafik](https://cloud.githubusercontent.com/assets/26893803/24792644/319d89e2-1b7f-11e7-8bc3-1d68e7baf993.png)

**Comment by giddie** [comment]
It's quite difficult to be sure of what I'm seeing in the screenshots, since the theme is so different. In the current version of the plugin, the DE translation for "Default Assignee" is "Standard Verantwortlicher", not "Standard Bearbeiter". Is there any chance this field is being offered by a different plugin?

![screenshot_20170407_095936](https://cloud.githubusercontent.com/assets/10906/24793250/35d23996-1b79-11e7-9a3e-259bcec44ede.png)

**Comment by GessDraeger** [comment]
It's exact the same field. I have modified the german translation to our needs.

I see, it' s not a problem in your plugin, because it works with the original version of redmine.
Anyway thanks for your effort
